services:
  webapi:
    image: devstudio35-hvejakg9fuhngyct.azurecr.io/webapi
    build:
      context: .
      dockerfile: webapi/Dockerfile

  webapplication1:
    image: devstudio35-hvejakg9fuhngyct.azurecr.io/webapp
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

